### ISSUE TITLE
Live Unit Testing With C# 8

### ISSUE THREAD

**Issue by jkvoch** [dotnet/csharplang#2049]
When using C# 8 nullable references with Visual Studio 2019, the Live Unit Testing feature doesn't work. The build always fails with error messages like "error CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' context.". I realize this is probably because I have the "Treat warnings as error" turned on but the solution builds fine as I have the nullable references turned on for all projects in the .csproj file.

Adding "#nullable enable" to the files with nullable references changes this error to:
```
[20:03:16.156 Error] - FatalError - System.ArgumentException: Inconsistent language versions
Parameter name: syntaxTrees
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonLanguageVersion(ImmutableArray`1 syntaxTrees)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation..ctor(String assemblyName, CSharpCompilationOptions options, ImmutableArray`1 references, CSharpCompilation previousSubmission, Type submissionReturnType, Type hostObjectType, Boolean isSubmission, ReferenceManager referenceManager, Boolean reuseReferenceManager, SyntaxAndDeclarationManager syntaxAndDeclarations, AsyncQueue`1 eventQueue)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.Update(ReferenceManager referenceManager, Boolean reuseReferenceManager, SyntaxAndDeclarationManager syntaxAndDeclarations)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.AddSyntaxTrees(IEnumerable`1 trees)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonAddSyntaxTrees(IEnumerable`1 trees)
   at Microsoft.CodeAnalysis.LiveUnitTesting.BuildManagement.CompilationComparer.GetUpdatedCompilation(Compilation compilation, CommandLineArguments arguments, Logger logger, BuildDifference& differences)
   at Microsoft.CodeAnalysis.LiveUnitTesting.BuildManagement.EmitHelper.<EmitAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.LiveUnitTesting.BuildManagement.BuildService.<EmitSingleProjectAsync>d__51.MoveNext()
```

I have C# 8 set as the language for all projects.

**Comment by CyrusNajmabadi** [comment]
Tagging @tannergooding .  Note: this should likely be migrated to dotnet/roslyn as this isn't a C# Language issue, but is a tooling problem.

**Comment by tannergooding** [comment]
@jkvoch, could you please move to Roslyn?

It would be worthwhile to tag @ManishJayaswal on the issue.
